In [13]:
import numpy as np

"""
This is an example from AI course
"""

N = 10000

v = np.zeros((N, 3))


immediate_rewards = [0, 0, 0]



for i in range(N - 1):
    
    v[i+1, 0] = 1.0 * (0+ 0.9 * v[i, 1])
    
    v[i+1, 1] = 1.0 * (0 + 0.9 * v[i, 2])
    
    v[i+1, 2] = 0.8 * (0 + 0.9 * v[i, 1]) + 0.2 * (10 + 0.9 * v[i, 0])
    
    
v




array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.        ],
       [0.        , 1.8       , 2.        ],
       ...,
       [7.85645005, 8.72938894, 9.69932105],
       [7.85645005, 8.72938894, 9.69932105],
       [7.85645005, 8.72938894, 9.69932105]])

In [23]:
import numpy as np

"""
This is an example from AI course
"""

N = 1000

v = np.zeros((N, 3))

R = [4, 0, 16]

for i in range(N - 1):
    
    v[i+1, 0] = 0.5 * (R[1] + 0.5 * v[i, 1]) + 0.5 * (R[0] + 0.5 * v[i, 0])
    
    v[i+1, 1] = 0.5 * (R[0] + 0.5 * v[i, 0]) + 0.5 * (R[2] + 0.5 * v[i, 2])
    
    v[i+1, 2] = 0.5 * (R[1] + 0.5 * v[i, 1]) + 0.5 * (R[2] + 0.5 * v[i, 2])
    
    
v

array([[ 0. ,  0. ,  0. ],
       [ 2. , 10. ,  8. ],
       [ 5. , 12.5, 12.5],
       ...,
       [ 8. , 16. , 16. ],
       [ 8. , 16. , 16. ],
       [ 8. , 16. , 16. ]])

In [25]:
import numpy as np

"""
This is an example from AI course
"""

N = 1000

v = np.zeros((N, 3))

R = [4, 0, 16]

for i in range(N - 1):
    
    v[i+1, 0] = 0.5 * (R[0] + 0.5 * v[i, 1]) + 0.5 * (R[0] + 0.5 * v[i, 0])
    
    v[i+1, 1] = 0.5 * (R[1] + 0.5 * v[i, 0]) + 0.5 * (R[1] + 0.5 * v[i, 2])
    
    v[i+1, 2] = 0.5 * (R[2] + 0.5 * v[i, 1]) + 0.5 * (R[2] + 0.5 * v[i, 2])
    
    
v

array([[ 0.,  0.,  0.],
       [ 4.,  0., 16.],
       [ 5.,  5., 20.],
       ...,
       [ 8.,  8., 24.],
       [ 8.,  8., 24.],
       [ 8.,  8., 24.]])

In [38]:

N = 10
V = np.zeros((N, 3))
T1 = np.array([[0.5, 0.5, 0], [0.5, 0, 0.5], [0, 0.5, 0.5]])
T2 = np.array([[0, 1, 0], [1, 0, 0], [1, 0, 0]])
R = np.array([-7,0,7])

discount = 0.5

for i in range(N-1):
    v_temp = []
    for s in range(3):
        a1 = R[s] + np.sum(discount * T1[s,:] @ V[i,:].T)
        a2 = R[s] + np.sum(discount * T2[s,:] @ V[i,:].T)
        v_temp.append(np.max([a1,a2]))
        
    V[i+1,:] = v_temp



v_temp


[-7.0, 0.0, 7.0]

In [29]:
np.array([[0.5, 0.5], [1, 0]])

array([0.5, 0.5])